### ISSUE TITLE
Throws when using inside of cssnext

### ISSUE THREAD

**Issue by Antontelesh** [postcss/postcss-selector-matches#5]
Here is the exception message:

```
.../node_modules/cssnext/dist/features.js:51
    return require("postcss-selector-matches")(options);
                                              ^
TypeError: object is not a function
```

Seems like `postcss-selector-matches` is no more a function.
Maybe v1.2.0 release should be a major one as it has breaking changes.

**Comment by MoOx** [comment]
The change is not intentional. I will push a fix.

**Comment by MoOx** [comment]
Fix released as 1.2.1, please uninstall and reinstall cssnext (this should update postcss-selector-matches to 1.2.1)

**Comment by bradbarrow** [comment]
Just scrambled to fix this in production...thanks for fixing it @MoOx 

I guess shrinkwrapping my repo was a valuable step to take either way.

**Comment by Antontelesh** [comment]
@MoOx thank you for the really quick fix!

**Comment by vigneshshanmugam** [comment]
@MoOx That was really fast. Thanks :)
